In [3]:
import numpy as np 
import pandas as pd

In [5]:
movies = pd.read_csv('tmdb_5000_movies.csv') 
credits = pd.read_csv('tmdb_5000_credits.csv')

<h2>preprocessing the data</h2>

In [5]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [7]:
credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [7]:
movies = movies.merge(credits, on='title')

In [11]:
movies.shape

(4809, 23)

In [13]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [9]:
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [17]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [11]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [13]:
movies.dropna(inplace=True)

In [23]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [25]:
movies.shape

(4806, 7)

In [27]:
movies.duplicated().sum()

0

In [37]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
#need the data as a list of values not a list of dictionaries 
import ast 
def convert(obj): 
    L = [] 
    for i in ast.literal_eval(obj): 
        L.append(i['name']) 
    return L

In [17]:
movies['genres'] = movies['genres'].apply(convert) 
movies['keywords'] = movies['keywords'].apply(convert)

In [19]:
def convert_3(obj): 
    L = [] 
    count = 0 
    for i in ast.literal_eval(obj): 
        if count != 3: 
            L.append(i['name']) 
            count = count+1 
        else: 
            break 
    return L

In [21]:
movies['cast'] = movies['cast'].apply(convert_3)

In [22]:
def fetch_director(obj): 
    L = [] 
    for i in ast.literal_eval(obj): 
        if i['job'] == 'Director': 
            L.append(i['name']) 
            break 

    return L

In [25]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [27]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [29]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])  
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])  
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])  
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [57]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]

In [31]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [61]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."

In [33]:
new_df = movies[['movie_id', 'title', 'tags']] 
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [35]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x)) 
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\LALITHA\AppData\Local\Temp\ipykernel_35748\3208700659.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))
C:\Users\LALITHA\AppData\Local\Temp\ipykernel_35748\3208700659.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

<h2>vectorization of text</h2>

In [37]:
import nltk 
from nltk.stem.porter import PorterStemmer 
ps = PorterStemmer() 

def stem(text): 
    y = []   

    for i in text.split(): 
        y.append(ps.stem(i)) 

    return " ".join(y)

In [39]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\LALITHA\AppData\Local\Temp\ipykernel_35748\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [74]:
new_df.head(1)

   movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a parapleg marin is dispa...

In [41]:
from sklearn.feature_extraction.text import CountVectorizer 

cv = CountVectorizer(max_features=5000, stop_words='english') 
vectors = cv.fit_transform(new_df['tags']).toarray()

In [80]:
vectors.shape

(4806, 5000)

<h2>recommender system functions  </h2>

In [43]:
from sklearn.metrics.pairwise import cosine_similarity 

similarity = cosine_similarity(vectors) 

#recommends top 5 movies most similar to the input movie 
def recommend(movie, top_k=5): 
    movie_index = new_df[new_df['title'] == movie].index[0]  
    distances = similarity[movie_index] 
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:top_k+1] 

    for i in movies_list: 
        print(new_df.iloc[i[0]].title)  

#how many of my top 5 recommended movies share at least one genre with the input movie 
def eval_rec(movie_title, top_k=5): 
    movie_index = new_df[new_df['title'] == movie_title].index[0]
    distances = similarity[movie_index] 

    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:top_k+1]

    target_genres = set(movies.iloc[movie_index]['genres']) 
    precision_scores = [] 

    for i in movies_list: 
        recommended_genres = set(movies.iloc[i[0]]['genres']) 
        overlap = len(target_genres & recommended_genres) 
        precision_scores.append(1 if overlap > 0 else 0) 

    precision = np.mean(precision_scores) 
    print(f"precision@{top_k}: {precision: .3f}") 

#how many different genres are represented in recommendations 
def evaluate_diversity(movie_title, top_k=5): 
    movie_index = new_df[new_df['title'] == movie_title].index[0] 
    distances = similarity[movie_index] 
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:top_k+1] 

    all_genres = set() 
    for i in movies_list:   
        all_genres.update(movies.iloc[i[0]]['genres']) 

    diversity_score = len(all_genres) / top_k 

    print(f"diversity score: {diversity_score: .3f}") 

#how unique are my recommendations compared to the input movie 
def evaluate_novelty(movie_title, top_k=5): 
    movie_index = new_df[new_df['title'] == movie_title].index[0] 
    distances = similarity[movie_index] 
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:top_k+1]

    top_indices = [i[0] for i in movies_list] 
    similarity_scores = [i[1] for i in movies_list]
    avg_similarity = np.mean(similarity_scores) 
    novelty_score = 1 - avg_similarity 

    print(f"novelty score: {novelty_score: .3f}") 
    return novelty_score

<h2>pickle stuff</h2>

In [115]:
import pickle 
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [118]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [120]:
pickle.dump(movies, open('movies_data.pkl', 'wb'))

<h2>testing the code  </h2>

In [86]:
recommend('The Dark Knight Rises')

The Dark Knight
Batman Returns
Batman
Batman Forever
Batman Begins

In [88]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [98]:
eval_rec('Avatar')

precision@5:  1.000

In [108]:
evaluate_diversity('Avatar')

diversity score:  1.600

In [110]:
evaluate_novelty('Avatar')

novelty score:  0.736

0.7355416446101316

In [112]:
evaluate_novelty('The Dark Knight Rises')

novelty score:  0.659

0.6593153793051518

In [55]:
sample_movies = new_df['title'].sample(2000, random_state=42) 

precision_list = [] 
diversity_list = [] 
novelty_list = [] 

for movie in sample_movies:   
    movie_index = new_df[new_df['title'] == movie].index[0]  
    if movie_index >= similarity.shape[0]: 
        print(f"skipping {movie_index}") 
        continue 
    
    distances = similarity[movie_index] 
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]  

    target_genres = set(movies.iloc[movie_index]['genres']) 
    precision_scores = []   

    for i in movie_list: 
        recommended_genres = set(movies.iloc[i[0]]['genres']) 
        overlap = len(target_genres & recommended_genres) 
        precision_scores.append(1 if overlap > 0 else 0) 
    precision = np.mean(precision_scores) 
    precision_list.append(precision) 

    all_genres = set() 
    for i in movie_list: 
        all_genres.update(movies.iloc[i[0]]['genres']) 
    diversity = len(all_genres) / len(movie_list) 
    diversity_list.append(diversity)   

    similarity_scores = [i[1] for i in movie_list]  
    avg_similarity = np.mean(similarity_scores) 
    novelty = 1 - avg_similarity 
    novelty_list.append(novelty)             

avg_precision = np.mean(precision_list)  
avg_diversity = np.mean(diversity_list) 
avg_novelty = np.mean(novelty_list)  

print(f"avg precision - f{avg_precision}")   
print(f"avg diversity - f{avg_diversity}")  
print(f"avg novelty - f{avg_novelty}")

skipping 4806
skipping 4808
avg precision - f0.8924924924924925
avg diversity - f1.1653653653653655
avg novelty - f0.7167671881777734